# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 034a2fa82f05b2dc9089fbe4ce6b7de63c987582800ca53ee715f1844c46211847247c74e3ddc4da0508cafa468cc37240c92ddd5dace8cb6c1b475cf03c9592

test:
  secret_key_base: db28d7363031cf3aff79c507efaab9d06bfe5a5062db2d081cdd8697677b93a9075b78d264d9a59909e525ac4e7650a3e90d90622c90296246d52c718320a621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
